### ISSUE TITLE
Stuck during boot

### ISSUE THREAD

**Issue by rvanlaar** [ladar/sedutil#12]
I'm using a lenovo X1 with an nvme SSD.

I've configured the SSD on another machine and followed the steps[1] for setting it up.

Now when I boot the laptop I only see the following in the top hand corner:
```
Loading bzImage... ok
Loading rootfs.cpio.xz... ok
```

That's all. I can't fill in a password, or anything else.
After a minute or two the system reboots.

What is the problem?

[1]
```
gunzip /usr/sedutil/UEFI64-*.img.gz

sedutil-cli --initialsetup PASSWORD /dev/nvme1
sedutil-cli --enablelockingrange 0 PASSWORD /dev/nvme1
sedutil-cli --setlockingrange 0 LK Admin1 PASSWORD /dev/nvme1
sedutil-cli --setmbrdone off Admin1 PASSWORD /dev/nvme1
sedutil-cli --loadpbaimage PASSWORD /usr/sedutil/UEFI64-*.img /dev/nvme1
sedutil-cli --setsidpassword PASSWORD PASSWORD /dev/nvme1
sedutil-cli --setmbrdone on Admin1 PASSWORD /dev/nvme1

```

**Comment by asahaf** [comment]
I'm facing the same issue

**Comment by rvanlaar** [comment]
I removed OPAL completely and tried using:
https://github.com/ChubbyAnt/sedutil sedutil.com 

That one boots and let's me enter the password.
One thing that was different, was that I had enabled csm. 

The ChubbyAnt version did let me enter a password. 
However, it wouldn't continue with the boot, i.e. it wouldn't boot windows.

**Comment by asahaf** [comment]
I'm using System76 Galago Pro with Samsung 970 Evo Plus SSD. I tried different sedutil images, with no luck. I had to do factory reset the drive, lost all data.
I don't have CSM option.

**Comment by rvanlaar** [comment]
I did two resets, without loosing data. I followed the steps here:
https://sedutil.com/

**Comment by asahaf** [comment]
running this command fails
```
sedutil-cli --revertnoerase debug /dev/nvme0
```
I had to do this
```
sedutil-cli --reverttper debug /dev/nvme0
```

Did you have success with ChubbyAnt/sedutil forked?

**Comment by ChubbyAnt** [comment]
@rvanlaar I think the X1 Thinkpad might poweroff the NVME during a soft reboot.

But, the good news is at least you can probably use hardware Bitlocker with the X1. At least that's something!

**Comment by asahaf** [comment]
I was able to encrypt my drive, but now when I enter the password, I says drive is unlocked but it doesn't reboot

**Comment by ChubbyAnt** [comment]
@asahaf did you try the https://SEDutil.com Rescue64 image and PBA?

**Comment by asahaf** [comment]
yes I did. it seems it freezes when it tries to reboot after unlocking the drive. I did try booting the Rescue and then executing reboot/shutdown command, it freezes too.

**Comment by ladar** [comment]
@rvanlaar I'm using `sedutils` on my ThinkPad P1, which is almost identical to the ThinkPad X1. 

It's been awhile since I went through my own quest to configure things properly. but I do recall there being a few critical BIOS settings. Off hand I believe they were setting the disk controller mode to AHCI. Setting the boot mode set to UEFI only, or if configured with "both," then UEFI set to first in the priority. Either way you'll need to ensure CSM support is enabled, and secure boot is disabled. You'll also need to ensure your UEFI boot priorities are correct. The OS should be ahead of the NVMe device, so that when you reboot after unlocking, you boot the OS, and not the PBA a second time.

Some of these items might be optional, I just don't recall what happens if you deviate. Specifically, I think AHCI  was needed to for software RAID support, so I don't recall how it impacted my `sedutil` setup. I believe the graphics mode, and the boot settings, namely quick boot, impacted the formatting, but I don't recall if they did anything else.

If you feel like it, perhaps you can add to the repo wiki any details you discovered regarding the use of sedutils and you're particular ThinkPad.

**Comment by ladar** [comment]
P.S. Feel free to reopen if my suggestions don't fix the problem.

**Comment by rvanlaar** [comment]
I won't be re-opening issues. 

The whole hassle of trying which combinations made it work took too much time.
I went with LUKS and bitlocker encryption in the end.

Thanks for the software though, I learned a lot about disk encryption.
